[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false


[programs.localnet]
voting = "5vxREM6UabKcfjo7RcwL2ECQ5mJsfRcUa9vnisDAH3Z6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
